import { getSupabaseBrowserClient } from "@/app/lib/supabase/client";

export type NotificationType =
  | "ORDER"
  | "APPOINTMENT"
  | "CANCELLATION"
  | "RESCHEDULE"
  | "CUSTOMER"
  | "LOW_INVENTORY"
  | "SUBSCRIPTION"
  | "TRIAL"
  | "PROMOTION"
  | "SYSTEM";

export interface BusinessNotification {
  id: string;
  tenantId: string;
  recipientId: string;
  type: NotificationType;
  title: string;
  message: string;
  href: string;
  isRead: boolean;
  readAt?: string;
  createdAt: string;
  metadata: Record<string, unknown>;
}

export type NotificationRow = {
  id: string;
  tenant_id: string;
  recipient_id: string;
  type: NotificationType;
  title: string;
  message: string;
  href: string | null;
  is_read: boolean;
  read_at: string | null;
  created_at: string;
  metadata: Record<string, unknown> | null;
};

export interface NotificationSnapshot {
  items: BusinessNotification[];
  unreadCount: number;
}

const NOTIFICATION_COLUMNS =
  "id,tenant_id,recipient_id,type,title,message,href,is_read,read_at,created_at,metadata";

function client() {
  const supabase = getSupabaseBrowserClient();
  if (!supabase) throw new Error("Supabase is not configured.");
  return supabase;
}

export function mapNotificationRow(row: NotificationRow): BusinessNotification {
  return {
    id: row.id,
    tenantId: row.tenant_id,
    recipientId: row.recipient_id,
    type: row.type,
    title: row.title,
    message: row.message,
    href: row.href ?? "/dashboard",
    isRead: row.is_read,
    readAt: row.read_at ?? undefined,
    createdAt: row.created_at,
    metadata: row.metadata ?? {},
  };
}

export async function enqueueDueNotifications(tenantId: string) {
  const { error } = await client().rpc("enqueue_due_business_notifications", {
    p_tenant_id: tenantId,
  });
  if (error) throw error;
}

export async function listNotifications(
  tenantId: string,
  recipientId: string,
): Promise<BusinessNotification[]> {
  const { data, error } = await client()
    .from("business_notifications")
    .select(NOTIFICATION_COLUMNS)
    .eq("tenant_id", tenantId)
    .eq("recipient_id", recipientId)
    .order("created_at", { ascending: false })
    .limit(50);

  if (error) throw error;
  return ((data ?? []) as NotificationRow[]).map(mapNotificationRow);
}

export async function getUnreadNotificationCount(
  tenantId: string,
  recipientId: string,
): Promise<number> {
  const { count, error } = await client()
    .from("business_notifications")
    .select("id", { count: "exact", head: true })
    .eq("tenant_id", tenantId)
    .eq("recipient_id", recipientId)
    .eq("is_read", false);

  if (error) throw error;
  return count ?? 0;
}

export async function getNotificationSnapshot(
  tenantId: string,
  recipientId: string,
): Promise<NotificationSnapshot> {
  // Trial alerts are generated by an in-app database function. Failure here
  // should not hide notifications that have already been saved.
  try {
    await enqueueDueNotifications(tenantId);
  } catch (error) {
    console.warn("Unable to enqueue due in-app notifications:", error);
  }

  const [items, unreadCount] = await Promise.all([
    listNotifications(tenantId, recipientId),
    getUnreadNotificationCount(tenantId, recipientId),
  ]);
  return { items, unreadCount };
}

export async function markNotificationRead(
  tenantId: string,
  recipientId: string,
  id: string,
) {
  const { error } = await client()
    .from("business_notifications")
    .update({ is_read: true, read_at: new Date().toISOString() })
    .eq("tenant_id", tenantId)
    .eq("recipient_id", recipientId)
    .eq("id", id)
    .eq("is_read", false);
  if (error) throw error;
}

export async function markAllNotificationsRead(
  tenantId: string,
  recipientId: string,
) {
  const { error } = await client()
    .from("business_notifications")
    .update({ is_read: true, read_at: new Date().toISOString() })
    .eq("tenant_id", tenantId)
    .eq("recipient_id", recipientId)
    .eq("is_read", false);
  if (error) throw error;
}

export async function deleteNotification(
  tenantId: string,
  recipientId: string,
  id: string,
) {
  const { error } = await client()
    .from("business_notifications")
    .delete()
    .eq("tenant_id", tenantId)
    .eq("recipient_id", recipientId)
    .eq("id", id);
  if (error) throw error;
}
