BEGIN;

-- Business owners manage their own teams. YuhBusiness controls the fixed role
-- model, plan seat allowances, paid-seat entitlements, and tenant isolation.

CREATE OR REPLACE FUNCTION public.team_plan_included_staff(p_plan TEXT)
RETURNS INTEGER
LANGUAGE SQL
IMMUTABLE
SET search_path = ''
AS $$
  SELECT CASE LOWER(COALESCE(p_plan, 'starter'))
    WHEN 'pro' THEN 1
    WHEN 'enterprise' THEN 2
    ELSE 0
  END;
$$;

CREATE OR REPLACE FUNCTION public.team_plan_max_staff(p_plan TEXT)
RETURNS INTEGER
LANGUAGE SQL
IMMUTABLE
SET search_path = ''
AS $$
  SELECT CASE LOWER(COALESCE(p_plan, 'starter'))
    WHEN 'pro' THEN 4
    WHEN 'enterprise' THEN 10
    ELSE 0
  END;
$$;

REVOKE ALL ON FUNCTION public.team_plan_included_staff(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.team_plan_max_staff(TEXT) FROM PUBLIC;

-- Every tenant receives the same protected business-role templates. Existing
-- ADMIN rows remain valid for backwards compatibility, but new assignments are
-- deliberately restricted to MANAGER or STAFF.
INSERT INTO public.roles (tenant_id, name, description, is_system_role)
SELECT tenant.id, role_template.name, role_template.description, TRUE
FROM public.tenants AS tenant
CROSS JOIN (
  VALUES
    ('MANAGER', 'Business manager with daily operations access'),
    ('STAFF', 'Staff member with operational access')
) AS role_template(name, description)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.roles existing_role
  WHERE existing_role.tenant_id = tenant.id
    AND UPPER(existing_role.name) = role_template.name
);

CREATE TABLE IF NOT EXISTS public.tenant_seat_entitlements (
  tenant_id UUID PRIMARY KEY REFERENCES public.tenants(id) ON DELETE CASCADE,
  paid_staff_seats INTEGER NOT NULL DEFAULT 0 CHECK (paid_staff_seats BETWEEN 0 AND 8),
  updated_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.tenant_seat_entitlements (tenant_id)
SELECT id FROM public.tenants
ON CONFLICT (tenant_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.team_invitations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  role_name TEXT NOT NULL CHECK (role_name IN ('MANAGER', 'STAFF')),
  token_hash TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED')),
  invited_by UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  accepted_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '72 hours'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  accepted_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS team_invitations_pending_email_idx
  ON public.team_invitations (tenant_id, LOWER(email))
  WHERE status = 'PENDING';
CREATE INDEX IF NOT EXISTS team_invitations_tenant_status_idx
  ON public.team_invitations (tenant_id, status, expires_at);

CREATE TABLE IF NOT EXISTS public.tenant_seat_change_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  requested_paid_seats INTEGER NOT NULL CHECK (requested_paid_seats BETWEEN 0 AND 8),
  status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
  requested_by UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  reviewed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  review_note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_seat_change_requests_one_pending_idx
  ON public.tenant_seat_change_requests (tenant_id)
  WHERE status = 'PENDING';

CREATE TABLE IF NOT EXISTS public.team_access_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  actor_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  subject_profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  invitation_id UUID REFERENCES public.team_invitations(id) ON DELETE SET NULL,
  details JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS team_access_events_tenant_created_idx
  ON public.team_access_events (tenant_id, created_at DESC);

ALTER TABLE public.tenant_seat_entitlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_seat_change_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_access_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.tenant_seat_entitlements FROM anon, authenticated;
REVOKE ALL ON TABLE public.team_invitations FROM anon, authenticated;
REVOKE ALL ON TABLE public.tenant_seat_change_requests FROM anon, authenticated;
REVOKE ALL ON TABLE public.team_access_events FROM anon, authenticated;

-- Membership and role writes are only available through the secured team RPCs.
-- Existing application flows only read these tables directly.
REVOKE INSERT, UPDATE, DELETE ON TABLE public.tenant_memberships FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.roles FROM authenticated;

CREATE OR REPLACE FUNCTION public.current_tenant_role(p_tenant_id UUID)
RETURNS TEXT
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT UPPER(role.name)
  FROM public.tenant_memberships membership
  JOIN public.roles role ON role.id = membership.role_id
  JOIN public.profiles profile ON profile.id = membership.profile_id
  WHERE membership.tenant_id = p_tenant_id
    AND membership.profile_id = auth.uid()
    AND membership.is_active = TRUE
    AND profile.is_active = TRUE
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.current_user_owns_tenant(p_tenant_id UUID)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT COALESCE(public.current_tenant_role(p_tenant_id) = 'OWNER', FALSE);
$$;

REVOKE ALL ON FUNCTION public.current_tenant_role(UUID) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.current_user_owns_tenant(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.current_tenant_role(UUID) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.current_user_owns_tenant(UUID) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.tenant_authorized_staff_capacity(p_tenant_id UUID)
RETURNS INTEGER
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT LEAST(
    public.team_plan_max_staff(tenant.plan),
    public.team_plan_included_staff(tenant.plan) + COALESCE(entitlement.paid_staff_seats, 0)
  )
  FROM public.tenants tenant
  LEFT JOIN public.tenant_seat_entitlements entitlement ON entitlement.tenant_id = tenant.id
  WHERE tenant.id = p_tenant_id;
$$;

REVOKE ALL ON FUNCTION public.tenant_authorized_staff_capacity(UUID) FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.enforce_tenant_staff_seat_limit()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_role TEXT;
  v_capacity INTEGER;
  v_active_staff INTEGER;
BEGIN
  IF NEW.is_active IS NOT TRUE THEN RETURN NEW; END IF;

  SELECT UPPER(role.name) INTO v_role
  FROM public.roles role
  WHERE role.id = NEW.role_id AND role.tenant_id = NEW.tenant_id;

  IF v_role NOT IN ('ADMIN', 'MANAGER', 'STAFF') THEN RETURN NEW; END IF;

  PERFORM PG_ADVISORY_XACT_LOCK(HASHTEXT('team-seats:' || NEW.tenant_id::TEXT));
  v_capacity := COALESCE(public.tenant_authorized_staff_capacity(NEW.tenant_id), 0);

  SELECT COUNT(*)::INTEGER INTO v_active_staff
  FROM public.tenant_memberships membership
  JOIN public.roles role ON role.id = membership.role_id
  WHERE membership.tenant_id = NEW.tenant_id
    AND membership.is_active = TRUE
    AND UPPER(role.name) IN ('ADMIN', 'MANAGER', 'STAFF')
    AND (TG_OP = 'INSERT' OR membership.id <> NEW.id);

  IF v_active_staff >= v_capacity THEN
    RAISE EXCEPTION 'This business has reached its authorized staff limit. Add a paid seat or change plans first.'
      USING ERRCODE = 'P0001';
  END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.enforce_tenant_staff_seat_limit() FROM PUBLIC;
DROP TRIGGER IF EXISTS trg_tenant_memberships_staff_seat_limit ON public.tenant_memberships;
CREATE TRIGGER trg_tenant_memberships_staff_seat_limit
BEFORE INSERT OR UPDATE OF role_id, is_active ON public.tenant_memberships
FOR EACH ROW EXECUTE FUNCTION public.enforce_tenant_staff_seat_limit();

-- A staff-only or manager-only account cannot turn its business membership
-- into an owner account by calling the additional-business RPC directly.
CREATE OR REPLACE FUNCTION public.guard_staff_only_business_creation()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.uid() IS NULL OR COALESCE(auth.role() = 'service_role', FALSE) OR public.is_super_admin() THEN
    RETURN NEW;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.tenant_memberships membership
    WHERE membership.profile_id = auth.uid() AND membership.is_active = TRUE
  ) AND NOT EXISTS (
    SELECT 1
    FROM public.tenant_memberships membership
    JOIN public.roles role ON role.id = membership.role_id
    WHERE membership.profile_id = auth.uid()
      AND membership.is_active = TRUE
      AND UPPER(role.name) = 'OWNER'
  ) THEN
    RAISE EXCEPTION 'Staff and managers cannot create businesses from a team account.'
      USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.guard_staff_only_business_creation() FROM PUBLIC;
DROP TRIGGER IF EXISTS trg_guard_staff_only_business_creation ON public.tenants;
CREATE TRIGGER trg_guard_staff_only_business_creation
BEFORE INSERT ON public.tenants
FOR EACH ROW EXECUTE FUNCTION public.guard_staff_only_business_creation();

CREATE OR REPLACE FUNCTION public.guard_tenant_plan_staff_capacity()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_capacity INTEGER;
  v_active INTEGER;
  v_paid INTEGER;
BEGIN
  IF NEW.plan IS NOT DISTINCT FROM OLD.plan THEN RETURN NEW; END IF;
  SELECT COALESCE(paid_staff_seats, 0) INTO v_paid
  FROM public.tenant_seat_entitlements WHERE tenant_id = NEW.id;
  IF COALESCE(v_paid, 0) > (
    public.team_plan_max_staff(NEW.plan) - public.team_plan_included_staff(NEW.plan)
  ) THEN
    RAISE EXCEPTION 'Reduce paid staff seats before changing this business plan.'
      USING ERRCODE = 'P0001';
  END IF;
  v_capacity := LEAST(
    public.team_plan_max_staff(NEW.plan),
    public.team_plan_included_staff(NEW.plan) + COALESCE(v_paid, 0)
  );
  SELECT COUNT(*)::INTEGER INTO v_active
  FROM public.tenant_memberships membership
  JOIN public.roles role ON role.id = membership.role_id
  WHERE membership.tenant_id = NEW.id AND membership.is_active = TRUE
    AND UPPER(role.name) IN ('ADMIN', 'MANAGER', 'STAFF');
  IF v_active > v_capacity THEN
    RAISE EXCEPTION 'Deactivate staff or authorize enough seats before changing this business plan.'
      USING ERRCODE = 'P0001';
  END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.guard_tenant_plan_staff_capacity() FROM PUBLIC;
DROP TRIGGER IF EXISTS trg_guard_tenant_plan_staff_capacity ON public.tenants;
CREATE TRIGGER trg_guard_tenant_plan_staff_capacity
BEFORE UPDATE OF plan ON public.tenants
FOR EACH ROW EXECUTE FUNCTION public.guard_tenant_plan_staff_capacity();

CREATE OR REPLACE FUNCTION public.get_tenant_team_summary(p_tenant_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_plan TEXT;
  v_included INTEGER;
  v_max INTEGER;
  v_paid INTEGER;
  v_capacity INTEGER;
  v_active_staff INTEGER;
  v_result JSONB;
BEGIN
  IF NOT public.current_user_owns_tenant(p_tenant_id) THEN
    RAISE EXCEPTION 'Only the business owner can manage Team & Access.' USING ERRCODE = '42501';
  END IF;

  UPDATE public.team_invitations
  SET status = 'EXPIRED'
  WHERE tenant_id = p_tenant_id AND status = 'PENDING' AND expires_at <= NOW();

  SELECT CASE LOWER(COALESCE(tenant.plan::TEXT, 'starter'))
    WHEN 'pro' THEN 'pro'
    WHEN 'enterprise' THEN 'enterprise'
    ELSE 'starter'
  END INTO v_plan
  FROM public.tenants tenant WHERE tenant.id = p_tenant_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Business not found.' USING ERRCODE = 'P0002'; END IF;

  INSERT INTO public.tenant_seat_entitlements (tenant_id)
  VALUES (p_tenant_id) ON CONFLICT (tenant_id) DO NOTHING;

  SELECT paid_staff_seats INTO v_paid
  FROM public.tenant_seat_entitlements WHERE tenant_id = p_tenant_id;
  v_included := public.team_plan_included_staff(v_plan);
  v_max := public.team_plan_max_staff(v_plan);
  v_capacity := LEAST(v_max, v_included + COALESCE(v_paid, 0));

  SELECT COUNT(*)::INTEGER INTO v_active_staff
  FROM public.tenant_memberships membership
  JOIN public.roles role ON role.id = membership.role_id
  WHERE membership.tenant_id = p_tenant_id
    AND membership.is_active = TRUE
    AND UPPER(role.name) IN ('ADMIN', 'MANAGER', 'STAFF');

  SELECT JSONB_BUILD_OBJECT(
    'tenantId', p_tenant_id,
    'plan', v_plan,
    'includedStaff', v_included,
    'maxStaff', v_max,
    'paidStaffSeats', COALESCE(v_paid, 0),
    'authorizedStaff', v_capacity,
    'activeStaff', v_active_staff,
    'additionalSeatPrice', 2,
    'monthlySeatCharge', COALESCE(v_paid, 0) * 2,
    'members', COALESCE((
      SELECT JSONB_AGG(JSONB_BUILD_OBJECT(
        'membershipId', membership.id,
        'profileId', profile.id,
        'name', COALESCE(NULLIF(BTRIM(profile.full_name), ''), SPLIT_PART(profile.email, '@', 1)),
        'email', profile.email,
        'role', LOWER(role.name),
        'isActive', membership.is_active,
        'joinedAt', membership.joined_at
      ) ORDER BY CASE WHEN UPPER(role.name) = 'OWNER' THEN 0 ELSE 1 END, membership.joined_at)
      FROM public.tenant_memberships membership
      JOIN public.roles role ON role.id = membership.role_id
      JOIN public.profiles profile ON profile.id = membership.profile_id
      WHERE membership.tenant_id = p_tenant_id
    ), '[]'::JSONB),
    'invitations', COALESCE((
      SELECT JSONB_AGG(JSONB_BUILD_OBJECT(
        'id', invitation.id,
        'email', invitation.email,
        'role', LOWER(invitation.role_name),
        'status', LOWER(invitation.status),
        'expiresAt', invitation.expires_at,
        'createdAt', invitation.created_at
      ) ORDER BY invitation.created_at DESC)
      FROM public.team_invitations invitation
      WHERE invitation.tenant_id = p_tenant_id
        AND invitation.status = 'PENDING'
    ), '[]'::JSONB),
    'pendingSeatRequest', (
      SELECT JSONB_BUILD_OBJECT(
        'id', request.id,
        'requestedPaidSeats', request.requested_paid_seats,
        'status', LOWER(request.status),
        'createdAt', request.created_at
      )
      FROM public.tenant_seat_change_requests request
      WHERE request.tenant_id = p_tenant_id AND request.status = 'PENDING'
      ORDER BY request.created_at DESC LIMIT 1
    )
  ) INTO v_result;

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.get_tenant_team_summary(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_tenant_team_summary(UUID) TO authenticated;

CREATE OR REPLACE FUNCTION public.create_team_invitation(
  p_tenant_id UUID,
  p_email TEXT,
  p_role_name TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_email TEXT := LOWER(BTRIM(COALESCE(p_email, '')));
  v_role TEXT := UPPER(BTRIM(COALESCE(p_role_name, '')));
  v_token TEXT := REPLACE(gen_random_uuid()::TEXT, '-', '')
    || REPLACE(gen_random_uuid()::TEXT, '-', '');
  v_invitation public.team_invitations;
  v_capacity INTEGER;
  v_active INTEGER;
  v_pending INTEGER;
BEGIN
  IF NOT public.current_user_owns_tenant(p_tenant_id) THEN
    RAISE EXCEPTION 'Only the business owner can invite team members.' USING ERRCODE = '42501';
  END IF;
  IF NOT public.tenant_subscription_allows_access(p_tenant_id) THEN
    RAISE EXCEPTION 'This business subscription is inactive.' USING ERRCODE = '42501';
  END IF;
  IF v_role NOT IN ('MANAGER', 'STAFF') THEN
    RAISE EXCEPTION 'Choose Manager or Staff.' USING ERRCODE = '22023';
  END IF;
  IF LENGTH(v_email) < 5 OR POSITION('@' IN v_email) < 2 THEN
    RAISE EXCEPTION 'Enter a valid staff email address.' USING ERRCODE = '22023';
  END IF;

  PERFORM PG_ADVISORY_XACT_LOCK(HASHTEXT('team-seats:' || p_tenant_id::TEXT));
  v_capacity := COALESCE(public.tenant_authorized_staff_capacity(p_tenant_id), 0);

  IF EXISTS (
    SELECT 1 FROM public.tenant_memberships membership
    JOIN public.profiles profile ON profile.id = membership.profile_id
    WHERE membership.tenant_id = p_tenant_id
      AND membership.is_active = TRUE
      AND LOWER(profile.email) = v_email
  ) THEN
    RAISE EXCEPTION 'This email already has access to the business.' USING ERRCODE = '23505';
  END IF;

  UPDATE public.team_invitations
  SET status = CASE WHEN expires_at <= NOW() THEN 'EXPIRED' ELSE 'REVOKED' END,
      revoked_at = CASE WHEN expires_at > NOW() THEN NOW() ELSE revoked_at END
  WHERE tenant_id = p_tenant_id AND LOWER(email) = v_email AND status = 'PENDING';

  SELECT COUNT(*)::INTEGER INTO v_active
  FROM public.tenant_memberships membership
  JOIN public.roles role ON role.id = membership.role_id
  WHERE membership.tenant_id = p_tenant_id
    AND membership.is_active = TRUE
    AND UPPER(role.name) IN ('ADMIN', 'MANAGER', 'STAFF');

  SELECT COUNT(*)::INTEGER INTO v_pending
  FROM public.team_invitations invitation
  WHERE invitation.tenant_id = p_tenant_id
    AND invitation.status = 'PENDING'
    AND invitation.expires_at > NOW();

  IF v_active + v_pending >= v_capacity THEN
    RAISE EXCEPTION 'No authorized staff seat is available. Request a paid seat or change plans first.'
      USING ERRCODE = 'P0001';
  END IF;

  INSERT INTO public.team_invitations (
    tenant_id, email, role_name, token_hash, invited_by
  ) VALUES (
    p_tenant_id,
    v_email,
    v_role,
    ENCODE(SHA256(CONVERT_TO(v_token, 'UTF8')), 'hex'),
    auth.uid()
  ) RETURNING * INTO v_invitation;

  INSERT INTO public.team_access_events (
    tenant_id, actor_id, action, invitation_id, details
  ) VALUES (
    p_tenant_id, auth.uid(), 'TEAM_INVITATION_CREATED', v_invitation.id,
    JSONB_BUILD_OBJECT('email', v_email, 'role', v_role, 'expiresAt', v_invitation.expires_at)
  );

  RETURN JSONB_BUILD_OBJECT(
    'id', v_invitation.id,
    'token', v_token,
    'email', v_email,
    'role', LOWER(v_role),
    'expiresAt', v_invitation.expires_at
  );
END;
$$;

REVOKE ALL ON FUNCTION public.create_team_invitation(UUID, TEXT, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_team_invitation(UUID, TEXT, TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.accept_team_invitation(
  p_token TEXT,
  p_full_name TEXT DEFAULT ''
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_auth_email TEXT;
  v_invitation public.team_invitations;
  v_role_id UUID;
  v_capacity INTEGER;
  v_active INTEGER;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Sign in with the invited email before accepting.' USING ERRCODE = '28000';
  END IF;

  SELECT LOWER(email) INTO v_auth_email FROM auth.users WHERE id = v_user_id;
  SELECT * INTO v_invitation
  FROM public.team_invitations invitation
  WHERE invitation.token_hash = ENCODE(
    SHA256(CONVERT_TO(COALESCE(p_token, ''), 'UTF8')),
    'hex'
  )
  FOR UPDATE;

  IF v_invitation.id IS NULL OR v_invitation.status <> 'PENDING' THEN
    RAISE EXCEPTION 'This invitation is invalid or has already been used.' USING ERRCODE = '22023';
  END IF;
  IF v_invitation.expires_at <= NOW() THEN
    UPDATE public.team_invitations SET status = 'EXPIRED' WHERE id = v_invitation.id;
    RAISE EXCEPTION 'This invitation has expired. Ask the owner for a new one.' USING ERRCODE = '22023';
  END IF;
  IF v_auth_email IS NULL OR v_auth_email <> LOWER(v_invitation.email) THEN
    RAISE EXCEPTION 'Sign in using the email address that received this invitation.' USING ERRCODE = '42501';
  END IF;
  IF NOT public.tenant_subscription_allows_access(v_invitation.tenant_id) THEN
    RAISE EXCEPTION 'This business subscription is inactive.' USING ERRCODE = '42501';
  END IF;

  PERFORM PG_ADVISORY_XACT_LOCK(HASHTEXT('team-seats:' || v_invitation.tenant_id::TEXT));
  v_capacity := COALESCE(public.tenant_authorized_staff_capacity(v_invitation.tenant_id), 0);

  SELECT COUNT(*)::INTEGER INTO v_active
  FROM public.tenant_memberships membership
  JOIN public.roles role ON role.id = membership.role_id
  WHERE membership.tenant_id = v_invitation.tenant_id
    AND membership.is_active = TRUE
    AND UPPER(role.name) IN ('ADMIN', 'MANAGER', 'STAFF')
    AND membership.profile_id <> v_user_id;

  IF v_active >= v_capacity THEN
    RAISE EXCEPTION 'This business no longer has an available staff seat.' USING ERRCODE = 'P0001';
  END IF;

  IF EXISTS (SELECT 1 FROM public.profiles WHERE id = v_user_id AND is_active = FALSE) THEN
    RAISE EXCEPTION 'This account has been deactivated.' USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.profiles (id, full_name, email, is_active)
  VALUES (
    v_user_id,
    COALESCE(NULLIF(BTRIM(p_full_name), ''), SPLIT_PART(v_auth_email, '@', 1)),
    v_auth_email,
    TRUE
  )
  ON CONFLICT (id) DO UPDATE
  SET full_name = CASE
        WHEN NULLIF(BTRIM(p_full_name), '') IS NOT NULL THEN BTRIM(p_full_name)
        ELSE public.profiles.full_name
      END,
      email = EXCLUDED.email,
      updated_at = NOW();

  SELECT id INTO v_role_id FROM public.roles
  WHERE tenant_id = v_invitation.tenant_id
    AND UPPER(name) = v_invitation.role_name
  LIMIT 1;
  IF v_role_id IS NULL THEN
    INSERT INTO public.roles (tenant_id, name, description, is_system_role)
    VALUES (
      v_invitation.tenant_id,
      v_invitation.role_name,
      CASE WHEN v_invitation.role_name = 'MANAGER'
        THEN 'Business manager with daily operations access'
        ELSE 'Staff member with operational access'
      END,
      TRUE
    ) RETURNING id INTO v_role_id;
  END IF;

  INSERT INTO public.tenant_memberships (tenant_id, profile_id, role_id, is_active)
  VALUES (v_invitation.tenant_id, v_user_id, v_role_id, TRUE)
  ON CONFLICT ON CONSTRAINT tenant_memberships_tenant_id_profile_id_key DO UPDATE
  SET role_id = EXCLUDED.role_id, is_active = TRUE;

  UPDATE public.team_invitations
  SET status = 'ACCEPTED', accepted_by = v_user_id, accepted_at = NOW()
  WHERE id = v_invitation.id;

  INSERT INTO public.team_access_events (
    tenant_id, actor_id, action, subject_profile_id, invitation_id, details
  ) VALUES (
    v_invitation.tenant_id, v_user_id, 'TEAM_INVITATION_ACCEPTED', v_user_id,
    v_invitation.id, JSONB_BUILD_OBJECT('role', v_invitation.role_name)
  );

  RETURN v_invitation.tenant_id;
END;
$$;

REVOKE ALL ON FUNCTION public.accept_team_invitation(TEXT, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.accept_team_invitation(TEXT, TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.update_team_member_role(
  p_tenant_id UUID,
  p_membership_id UUID,
  p_role_name TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_role TEXT := UPPER(BTRIM(COALESCE(p_role_name, '')));
  v_role_id UUID;
  v_subject UUID;
BEGIN
  IF NOT public.current_user_owns_tenant(p_tenant_id) THEN
    RAISE EXCEPTION 'Only the business owner can change team roles.' USING ERRCODE = '42501';
  END IF;
  IF v_role NOT IN ('MANAGER', 'STAFF') THEN
    RAISE EXCEPTION 'Choose Manager or Staff.' USING ERRCODE = '22023';
  END IF;

  SELECT membership.profile_id INTO v_subject
  FROM public.tenant_memberships membership
  JOIN public.roles role ON role.id = membership.role_id
  WHERE membership.id = p_membership_id
    AND membership.tenant_id = p_tenant_id
    AND membership.is_active = TRUE
    AND UPPER(role.name) <> 'OWNER';
  IF v_subject IS NULL THEN RAISE EXCEPTION 'Team member not found.' USING ERRCODE = 'P0002'; END IF;

  SELECT id INTO v_role_id FROM public.roles
  WHERE tenant_id = p_tenant_id AND UPPER(name) = v_role LIMIT 1;
  IF v_role_id IS NULL THEN RAISE EXCEPTION 'Business role is not configured.' USING ERRCODE = 'P0002'; END IF;

  UPDATE public.tenant_memberships SET role_id = v_role_id
  WHERE id = p_membership_id AND tenant_id = p_tenant_id;

  INSERT INTO public.team_access_events (tenant_id, actor_id, action, subject_profile_id, details)
  VALUES (p_tenant_id, auth.uid(), 'TEAM_ROLE_CHANGED', v_subject, JSONB_BUILD_OBJECT('role', v_role));
END;
$$;

CREATE OR REPLACE FUNCTION public.deactivate_team_member(
  p_tenant_id UUID,
  p_membership_id UUID
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_subject UUID;
BEGIN
  IF NOT public.current_user_owns_tenant(p_tenant_id) THEN
    RAISE EXCEPTION 'Only the business owner can remove team access.' USING ERRCODE = '42501';
  END IF;

  SELECT membership.profile_id INTO v_subject
  FROM public.tenant_memberships membership
  JOIN public.roles role ON role.id = membership.role_id
  WHERE membership.id = p_membership_id
    AND membership.tenant_id = p_tenant_id
    AND membership.is_active = TRUE
    AND UPPER(role.name) <> 'OWNER';
  IF v_subject IS NULL THEN RAISE EXCEPTION 'Team member not found.' USING ERRCODE = 'P0002'; END IF;

  UPDATE public.tenant_memberships SET is_active = FALSE
  WHERE id = p_membership_id AND tenant_id = p_tenant_id;

  INSERT INTO public.team_access_events (tenant_id, actor_id, action, subject_profile_id)
  VALUES (p_tenant_id, auth.uid(), 'TEAM_MEMBER_DEACTIVATED', v_subject);
END;
$$;

CREATE OR REPLACE FUNCTION public.revoke_team_invitation(
  p_tenant_id UUID,
  p_invitation_id UUID
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NOT public.current_user_owns_tenant(p_tenant_id) THEN
    RAISE EXCEPTION 'Only the business owner can revoke invitations.' USING ERRCODE = '42501';
  END IF;

  UPDATE public.team_invitations
  SET status = 'REVOKED', revoked_at = NOW()
  WHERE id = p_invitation_id AND tenant_id = p_tenant_id AND status = 'PENDING';
  IF NOT FOUND THEN RAISE EXCEPTION 'Pending invitation not found.' USING ERRCODE = 'P0002'; END IF;

  INSERT INTO public.team_access_events (tenant_id, actor_id, action, invitation_id)
  VALUES (p_tenant_id, auth.uid(), 'TEAM_INVITATION_REVOKED', p_invitation_id);
END;
$$;

REVOKE ALL ON FUNCTION public.update_team_member_role(UUID, UUID, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.deactivate_team_member(UUID, UUID) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.revoke_team_invitation(UUID, UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.update_team_member_role(UUID, UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.deactivate_team_member(UUID, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_team_invitation(UUID, UUID) TO authenticated;

CREATE OR REPLACE FUNCTION public.request_tenant_paid_staff_seats(
  p_tenant_id UUID,
  p_requested_paid_seats INTEGER
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_plan TEXT;
  v_max_paid INTEGER;
  v_current_paid INTEGER;
  v_request_id UUID;
BEGIN
  IF NOT public.current_user_owns_tenant(p_tenant_id) THEN
    RAISE EXCEPTION 'Only the business owner can request additional seats.' USING ERRCODE = '42501';
  END IF;
  SELECT LOWER(COALESCE(plan, 'starter')) INTO v_plan FROM public.tenants WHERE id = p_tenant_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Business not found.' USING ERRCODE = 'P0002'; END IF;
  IF NOT public.tenant_subscription_allows_access(p_tenant_id) THEN
    RAISE EXCEPTION 'This business subscription is inactive.' USING ERRCODE = '42501';
  END IF;
  v_max_paid := public.team_plan_max_staff(v_plan) - public.team_plan_included_staff(v_plan);
  IF p_requested_paid_seats < 1 OR p_requested_paid_seats > v_max_paid THEN
    RAISE EXCEPTION 'Choose a paid-seat total allowed by this plan.' USING ERRCODE = '22023';
  END IF;
  SELECT COALESCE(paid_staff_seats, 0) INTO v_current_paid
  FROM public.tenant_seat_entitlements WHERE tenant_id = p_tenant_id;
  IF p_requested_paid_seats <= COALESCE(v_current_paid, 0) THEN
    RAISE EXCEPTION 'Request a paid-seat total above the currently approved amount.' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.tenant_seat_change_requests (tenant_id, requested_paid_seats, requested_by)
  VALUES (p_tenant_id, p_requested_paid_seats, auth.uid())
  ON CONFLICT (tenant_id) WHERE status = 'PENDING' DO UPDATE
  SET requested_paid_seats = EXCLUDED.requested_paid_seats,
      requested_by = EXCLUDED.requested_by,
      created_at = NOW()
  RETURNING id INTO v_request_id;

  INSERT INTO public.team_access_events (tenant_id, actor_id, action, details)
  VALUES (
    p_tenant_id, auth.uid(), 'PAID_STAFF_SEATS_REQUESTED',
    JSONB_BUILD_OBJECT('requestedPaidSeats', p_requested_paid_seats, 'monthlyCharge', p_requested_paid_seats * 2)
  );
  RETURN v_request_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_tenant_seat_admin_summary(p_tenant_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_result JSONB;
BEGIN
  IF NOT public.is_super_admin() THEN
    RAISE EXCEPTION 'Only a platform administrator can review paid seats.' USING ERRCODE = '42501';
  END IF;
  SELECT JSONB_BUILD_OBJECT(
    'paidStaffSeats', COALESCE(entitlement.paid_staff_seats, 0),
    'includedStaff', public.team_plan_included_staff(tenant.plan),
    'maxStaff', public.team_plan_max_staff(tenant.plan),
    'additionalSeatPrice', 2,
    'activeStaff', (
      SELECT COUNT(*)::INTEGER FROM public.tenant_memberships membership
      JOIN public.roles role ON role.id = membership.role_id
      WHERE membership.tenant_id = tenant.id AND membership.is_active = TRUE
        AND UPPER(role.name) IN ('ADMIN', 'MANAGER', 'STAFF')
    ),
    'pendingRequest', (
      SELECT JSONB_BUILD_OBJECT(
        'id', request.id,
        'requestedPaidSeats', request.requested_paid_seats,
        'createdAt', request.created_at
      )
      FROM public.tenant_seat_change_requests request
      WHERE request.tenant_id = tenant.id AND request.status = 'PENDING'
      ORDER BY request.created_at DESC LIMIT 1
    )
  ) INTO v_result
  FROM public.tenants tenant
  LEFT JOIN public.tenant_seat_entitlements entitlement ON entitlement.tenant_id = tenant.id
  WHERE tenant.id = p_tenant_id;
  IF v_result IS NULL THEN RAISE EXCEPTION 'Business not found.' USING ERRCODE = 'P0002'; END IF;
  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_tenant_paid_staff_seats(
  p_tenant_id UUID,
  p_paid_staff_seats INTEGER,
  p_request_id UUID DEFAULT NULL,
  p_review_note TEXT DEFAULT ''
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_plan TEXT;
  v_max_paid INTEGER;
  v_included INTEGER;
  v_active INTEGER;
  v_current_paid INTEGER;
BEGIN
  IF NOT public.is_super_admin() THEN
    RAISE EXCEPTION 'Only a platform administrator can approve paid seats.' USING ERRCODE = '42501';
  END IF;
  SELECT LOWER(COALESCE(plan, 'starter')) INTO v_plan FROM public.tenants WHERE id = p_tenant_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Business not found.' USING ERRCODE = 'P0002'; END IF;
  v_included := public.team_plan_included_staff(v_plan);
  v_max_paid := public.team_plan_max_staff(v_plan) - v_included;
  IF p_paid_staff_seats < 0 OR p_paid_staff_seats > v_max_paid THEN
    RAISE EXCEPTION 'Paid staff seats exceed this plan allowance.' USING ERRCODE = '22023';
  END IF;
  SELECT COALESCE(paid_staff_seats, 0) INTO v_current_paid
  FROM public.tenant_seat_entitlements WHERE tenant_id = p_tenant_id;
  IF p_paid_staff_seats > COALESCE(v_current_paid, 0)
     AND NULLIF(BTRIM(COALESCE(p_review_note, '')), '') IS NULL THEN
    RAISE EXCEPTION 'Enter the confirmed payment reference before adding paid seats.' USING ERRCODE = '22023';
  END IF;

  SELECT COUNT(*)::INTEGER INTO v_active
  FROM public.tenant_memberships membership
  JOIN public.roles role ON role.id = membership.role_id
  WHERE membership.tenant_id = p_tenant_id AND membership.is_active = TRUE
    AND UPPER(role.name) IN ('ADMIN', 'MANAGER', 'STAFF');
  IF v_active > v_included + p_paid_staff_seats THEN
    RAISE EXCEPTION 'Deactivate staff before reducing the authorized seat total.' USING ERRCODE = 'P0001';
  END IF;

  INSERT INTO public.tenant_seat_entitlements (tenant_id, paid_staff_seats, updated_by, updated_at)
  VALUES (p_tenant_id, p_paid_staff_seats, auth.uid(), NOW())
  ON CONFLICT (tenant_id) DO UPDATE
  SET paid_staff_seats = EXCLUDED.paid_staff_seats,
      updated_by = EXCLUDED.updated_by,
      updated_at = NOW();

  IF p_request_id IS NOT NULL THEN
    UPDATE public.tenant_seat_change_requests
    SET status = 'APPROVED', reviewed_by = auth.uid(), reviewed_at = NOW(), review_note = NULLIF(BTRIM(p_review_note), '')
    WHERE id = p_request_id
      AND tenant_id = p_tenant_id
      AND status = 'PENDING'
      AND requested_paid_seats = p_paid_staff_seats;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'The pending seat request no longer matches this approval.' USING ERRCODE = 'P0002';
    END IF;
  END IF;

  INSERT INTO public.team_access_events (tenant_id, actor_id, action, details)
  VALUES (
    p_tenant_id, auth.uid(), 'PAID_STAFF_SEATS_SET',
    JSONB_BUILD_OBJECT('paidStaffSeats', p_paid_staff_seats, 'monthlyCharge', p_paid_staff_seats * 2, 'note', p_review_note)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.reject_tenant_paid_staff_seat_request(
  p_tenant_id UUID,
  p_request_id UUID,
  p_review_note TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NOT public.is_super_admin() THEN
    RAISE EXCEPTION 'Only a platform administrator can review paid seats.' USING ERRCODE = '42501';
  END IF;
  IF NULLIF(BTRIM(COALESCE(p_review_note, '')), '') IS NULL THEN
    RAISE EXCEPTION 'Enter a reason for rejecting this request.' USING ERRCODE = '22023';
  END IF;
  UPDATE public.tenant_seat_change_requests
  SET status = 'REJECTED', reviewed_by = auth.uid(), reviewed_at = NOW(), review_note = BTRIM(p_review_note)
  WHERE id = p_request_id AND tenant_id = p_tenant_id AND status = 'PENDING';
  IF NOT FOUND THEN RAISE EXCEPTION 'Pending seat request not found.' USING ERRCODE = 'P0002'; END IF;
  INSERT INTO public.team_access_events (tenant_id, actor_id, action, details)
  VALUES (p_tenant_id, auth.uid(), 'PAID_STAFF_SEATS_REJECTED', JSONB_BUILD_OBJECT('requestId', p_request_id, 'note', p_review_note));
END;
$$;

REVOKE ALL ON FUNCTION public.request_tenant_paid_staff_seats(UUID, INTEGER) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_tenant_seat_admin_summary(UUID) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.set_tenant_paid_staff_seats(UUID, INTEGER, UUID, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.reject_tenant_paid_staff_seat_request(UUID, UUID, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.request_tenant_paid_staff_seats(UUID, INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_tenant_seat_admin_summary(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_tenant_paid_staff_seats(UUID, INTEGER, UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reject_tenant_paid_staff_seat_request(UUID, UUID, TEXT) TO authenticated;

-- Replace the broad membership write policy with fixed business roles. Reads
-- remain membership-scoped; writes are further narrowed by restrictive rules,
-- so older permissive policies cannot grant Staff access to owner controls.
DO $$
DECLARE
  v_table TEXT;
BEGIN
  FOREACH v_table IN ARRAY ARRAY[
    'business_settings', 'business_modules', 'business_hours', 'categories',
    'products', 'services', 'staff', 'staff_services'
  ] LOOP
    IF TO_REGCLASS(FORMAT('public.%I', v_table)) IS NOT NULL
       AND EXISTS (
         SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = v_table AND column_name = 'tenant_id'
       ) THEN
      EXECUTE FORMAT('DROP POLICY IF EXISTS team_admin_insert_required ON public.%I', v_table);
      EXECUTE FORMAT('DROP POLICY IF EXISTS team_admin_update_required ON public.%I', v_table);
      EXECUTE FORMAT('DROP POLICY IF EXISTS team_admin_delete_required ON public.%I', v_table);
      EXECUTE FORMAT(
        'CREATE POLICY team_admin_insert_required ON public.%I AS RESTRICTIVE FOR INSERT TO authenticated
         WITH CHECK (public.is_super_admin() OR public.current_tenant_role(tenant_id) IN (''OWNER'', ''MANAGER'', ''ADMIN''))', v_table);
      EXECUTE FORMAT(
        'CREATE POLICY team_admin_update_required ON public.%I AS RESTRICTIVE FOR UPDATE TO authenticated
         USING (public.is_super_admin() OR public.current_tenant_role(tenant_id) IN (''OWNER'', ''MANAGER'', ''ADMIN''))
         WITH CHECK (public.is_super_admin() OR public.current_tenant_role(tenant_id) IN (''OWNER'', ''MANAGER'', ''ADMIN''))', v_table);
      EXECUTE FORMAT(
        'CREATE POLICY team_admin_delete_required ON public.%I AS RESTRICTIVE FOR DELETE TO authenticated
         USING (public.is_super_admin() OR public.current_tenant_role(tenant_id) IN (''OWNER'', ''MANAGER'', ''ADMIN''))', v_table);
    END IF;
  END LOOP;

  FOREACH v_table IN ARRAY ARRAY[
    'customers', 'orders', 'order_items', 'appointments', 'appointment_services'
  ] LOOP
    IF TO_REGCLASS(FORMAT('public.%I', v_table)) IS NOT NULL
       AND EXISTS (
         SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = v_table AND column_name = 'tenant_id'
       ) THEN
      EXECUTE FORMAT('DROP POLICY IF EXISTS team_operations_insert_required ON public.%I', v_table);
      EXECUTE FORMAT('DROP POLICY IF EXISTS team_operations_update_required ON public.%I', v_table);
      EXECUTE FORMAT('DROP POLICY IF EXISTS team_operations_delete_required ON public.%I', v_table);
      EXECUTE FORMAT(
        'CREATE POLICY team_operations_insert_required ON public.%I AS RESTRICTIVE FOR INSERT TO authenticated
         WITH CHECK (public.is_super_admin() OR public.current_tenant_role(tenant_id) IN (''OWNER'', ''MANAGER'', ''ADMIN'', ''STAFF''))', v_table);
      EXECUTE FORMAT(
        'CREATE POLICY team_operations_update_required ON public.%I AS RESTRICTIVE FOR UPDATE TO authenticated
         USING (public.is_super_admin() OR public.current_tenant_role(tenant_id) IN (''OWNER'', ''MANAGER'', ''ADMIN'', ''STAFF''))
         WITH CHECK (public.is_super_admin() OR public.current_tenant_role(tenant_id) IN (''OWNER'', ''MANAGER'', ''ADMIN'', ''STAFF''))', v_table);
      EXECUTE FORMAT(
        'CREATE POLICY team_operations_delete_required ON public.%I AS RESTRICTIVE FOR DELETE TO authenticated
         USING (public.is_super_admin() OR public.current_tenant_role(tenant_id) IN (''OWNER'', ''MANAGER'', ''ADMIN''))', v_table);
    END IF;
  END LOOP;
END;
$$;

DROP POLICY IF EXISTS tenant_owner_update_required ON public.tenants;
CREATE POLICY tenant_owner_update_required
  ON public.tenants AS RESTRICTIVE
  FOR UPDATE TO authenticated
  USING (public.is_super_admin() OR public.current_tenant_role(id) = 'OWNER')
  WITH CHECK (public.is_super_admin() OR public.current_tenant_role(id) = 'OWNER');

NOTIFY pgrst, 'reload schema';

COMMIT;
